modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/TheIllusiveC4/CustomFoV/issues"
displayURL="${mod_url}"
logoFile="${mod_icon}"
authors="${mod_author}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description='''
${mod_description}
'''
[[dependencies.customfov]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.customfov]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="CLIENT"